### ISSUE TITLE
getting an error when running train.py

### ISSUE THREAD

**Issue by gayalkuruppu** [gcucurull/visual-compatibility#13]
I downloaded the dataset polyvore and prepared the dataset as guided. but when I run 
`python train.py -d polyvore` it is giving me this error. Can someone help me out? Thank you
````
initializing dataloader...
init phase: train
feats_file = data/polyvore/dataset/features_train.npz
init phase: valid
feats_file = data/polyvore/dataset/features_valid.npz
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    dl = DataLoaderPolyvore()
  File "/home/gayalkuruppu_gk/visual-compatibility/dataloaders/Polyvore.py", line 13, in __init__
    super(DataLoaderPolyvore, self).__init__(path='data/polyvore/dataset/')
  File "/home/gayalkuruppu_gk/visual-compatibility/dataloaders/Dataloader.py", line 18, in __init__
    self.init_phase('valid')
  File "/home/gayalkuruppu_gk/visual-compatibility/dataloaders/Polyvore.py", line 26, in init_phase
    node_features = sp.load_npz(feats_file)
  File "/home/gayalkuruppu_gk/anaconda3/envs/context/lib/python3.6/site-packages/scipy/sparse/_matrix_io.py", line 142, in load_
npz
    return cls((loaded['data'], loaded['indices'], loaded['indptr']), shape=loaded['shape'])
  File "/home/gayalkuruppu_gk/anaconda3/envs/context/lib/python3.6/site-packages/numpy/lib/npyio.py", line 235, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/gayalkuruppu_gk/anaconda3/envs/context/lib/python3.6/site-packages/numpy/lib/format.py", line 683, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "/home/gayalkuruppu_gk/anaconda3/envs/context/lib/python3.6/site-packages/numpy/lib/format.py", line 822, in _read_bytes
    r = fp.read(size - len(data))
  File "/home/gayalkuruppu_gk/anaconda3/envs/context/lib/python3.6/zipfile.py", line 872, in read
    data = self._read1(n)
  File "/home/gayalkuruppu_gk/anaconda3/envs/context/lib/python3.6/zipfile.py", line 948, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```

**Comment by gayalkuruppu** [comment]
Preprocessing the data again solved this error for me.
