### ISSUE TITLE
why val Acc > train Acc?

### ISSUE THREAD

**Issue by sflvsm** [gcucurull/visual-compatibility#4]
When training this Gae model,I found val _acc is always higher than train_acc and when testing  test_acc is a little higher than val_acc.What caused it？

**Comment by gcucurull** [comment]
To avoid heavy over-fitting to the training data and structure, the model is regularized during training by applying dropout to the features and also to the connections (we call it support_dropout).

Therefore during training it never has access to all the information needed to make a perfect prediction. That could be the reason why the accuracy during training is lower.

**Comment by sflvsm** [comment]
Thank you very much for your reply!
I would also like to ask you on what device you training the model ?
When I trained it  and set k=15（-deg 15），it caused memoryError and showed
“ Invalid argument: Cannot use GPU when output.shape[1] * nnz(a) > 2^31”

**Comment by gcucurull** [comment]
Which dataset are you using? It was trained on a 12GB GPU.

**Comment by sflvsm** [comment]
polyvore resampled：
`Settings:
{'dataset': 'polyvore', 'learning_rate': 0.001, 'weight_decay': 0.0, 'epochs': 4000, 'hidden': [350, 350, 350], 'dropout': 0.5, 'degree': 15, 'summaries_dir': 'logs/', 'support_dropout': 0.15, 'write_summary': False, 'batch_norm': True, 'amz_data': 'Men_bought_together'}

initializing dataloader...
init phase: train
init phase: valid
init phase: test
get phase: train
Sampling negative edges...
Sampling done, time elapsed: 11.465760231018066
get phase: valid
Sampling negative edges...
Sampling done, time elapsed: 0.8183982372283936
get phase: test
Sampling negative edges...
Sampling done, time elapsed: 1.6916999816894531
Computing adj matrices up to 15th degree
/export/anaconda3/envs/tf/lib/python3.6/site-packages/scipy/sparse/_index.py:127: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    train_support = get_degree_supports(adj_train, DEGREE, adj_self_con=ADJ_SELF_CONNECTIONS)
  File "/export/shifan/visual-compatibility/utils.py", line 71, in get_degree_supports
    new_adj = ((pow) == 1).astype(np.float64)
  File "/export/anaconda3/envs/tf/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 231, in __eq__
    return self._scalar_binopt(other, operator.eq)
  File "/export/anaconda3/envs/tf/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 213, in _scalar_binopt
    res = self._with_data(op(self.data, other), copy=True)
  File "/export/anaconda3/envs/tf/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 1201, in _with_data
    return self.__class__((data, self.indices.copy(),
MemoryError
`

my own dataset：
`Training...
2019-11-08 00:34:16.751532: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
Traceback (most recent call last):
  File "/export/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/export/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/export/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[{{node gcn_1/SparseTensorDenseMatMul_5/SparseTensorDenseMatMul}}]]
	 [[add_1/_183]]
  (1) Invalid argument: Cannot use GPU when output.shape[1] * nnz(a) > 2^31
	 [[{{node gcn_1/SparseTensorDenseMatMul_5/SparseTensorDenseMatMul}}]]
0 successful operations.
0 derived errors ignored.
`

**Comment by gcucurull** [comment]
Oh I see what you mean now, we used a degree of 1 during training, so it is possible that deg=15 doesn't fit in memory. Try with a smaller degree.

**Comment by sflvsm** [comment]
thx！
